language: node_js
before_install:
  - npm install -g cucumber
node_js:
  - "iojs"
  
# whitelist
branches:
  only:
    - master  

before_script:
  - "curl -O http://selenium-release.storage.googleapis.com/2.47/selenium-server-standalone-2.47.1.jar"
  - "java -jar selenium-server-standalone-2.47.1.jar 2>&1 >/dev/null &"
  - "sleep 10"
